freekukan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls'))
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

region/models.py
from django.db import models

# Create your models here.


class Region(models.Model):
    name = models.CharField(max_length=4)

    def __str__(self):
        return self.name

user/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class User(models.Model):
    first_name = models.CharField(max_length=5)
    last_name = models.CharField(max_length=5)
    first_name_kana = models.CharField(max_length=10)
    last_name_kana = models.CharField(max_length=10)
    
    birth_date = models.DateField()
    
    phone = models.CharField(max_length=11)
    
    zip_code = models.CharField(max_length=7)
    region = models.ForeignKey(
        'region.Region',
        on_delete=models.PROTECT
    )
    address = models.CharField(max_length=255)
    
    comment = models.CharField(max_length=255, null=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return (self.last_name + self.first_name)

    def get_absolute_url(self):
        return reverse('user:detail', kwargs={'pk': self.pk})

region/views.py
from django.shortcuts import render

# Create your views here.

user/views.py
from django.views import generic
from django.urls import reverse_lazy
from .models import User

# Create your views here.


class IndexView(generic.ListView):
    model = User


class DetailView(generic.DetailView):
    model = User


class CreateView(generic.edit.CreateView):
    model = User
    fields = '__all__'


class UpdateView(generic.edit.UpdateView):
    model = User
    fields = '__all__' 


class DeleteView(generic.edit.DeleteView):
    model = User
    success_url = reverse_lazy('user:index')

user/templates/user/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
        <style>body {padding-top: 80px;}</style>
        <title>User</title>
    </head>
    
    <body>
        <nav class='navbar navbar-expand-sm navbar-dark bg-dark fixed-top'>
            <a class='navbar-brand' href='{% url "user:index" %}'>User</a>
        </nav>
        
        <div class='container'>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

user/templates/user/user_confirm_delete.html
{% extends './base.html' %}
{% block content %}
    <h1>記事の削除</h1>
    <p>'{{ object.name }}'を削除しますか?</p>
    <form action='' method='post'>{% csrf_token %}
        <button type='submit' class='submit delete'>削除する</button>
    </form>

    <div>
        <p><a href='JavaScript:history.back()'>戻る</a></p>
    </div>
{% endblock %}

user/templates/user/user_detail.html
{% extends './base.html' %}
{% block content %}
    <h1>{{ user.last_name }}{{ user.first_name }}</h1>
    <div>
        <p>{{ user.last_name_kana }}{{ user.first_name_kana }}</p>
        <p>{{ user.birth_date }}</p>
        <p>{{ user.phone }}</p>
        <p>{{ user.zip_code }}</p>
        <p>{{ user.region }}</p>
        <p>{{ user.address }}</p>
        <p>{{ user.comment }}</p>
    </div>
    <div>
        <a href='{% url "user:update" user.pk %}'>編集</a> |
        <a href='{% url "user:delete" user.pk %}'>削除</a>
    </div>
    <div>
        <a href='{% url "user:index" %}'>一覧へ戻る</a>
    </div>
{% endblock %}

user/templates/user/user_form.html
{% extends './base.html' %}
{% block content %}
    <h1>会員情報{{ object|yesno:'更新,登録'}}</h1>

    <form action='' method='post'>{% csrf_token %}
        {{ form.as_p }}
        <button type='submit' class='submit'>{{ object|yesno:'更新,登録'}}</button>
    </form>
    <div>
        <a href='JavaScript:history.back()'>戻る</a>
    </div>
{% endblock %}

user/templates/user/user_list.html
{% extends './base.html' %}
{% block content %}
    <h1>会員一覧</h1>

    <table class='table table-striped table-hover'>
        <tr>
            <th>ID</th>
            <th>氏名</th>
        </tr>
        
        {% for user in object_list %}
            <tr>
                <td>
                    {{ user.id }}
                </td>
                <td>
                    <a href='{% url "user:detail" user.pk %}'>{{ user.last_name }}{{ user.first_name }}</a>
                </td>
            </tr>
        {% endfor %}
    </table>

    <a href='{% url "user:create" %}'>会員登録</a>
{% endblock %}